display_name: "Test Display"

background_image: "media/dark.jpg"
background_color: "#000000"

logo: "media/logo.png"
logo_text:
  text: "Welcome to I04!"
  font: "Arial"
  size: 80
  color: "#feda1a"
  top_percent: 3
  left_percent: 2

clock:
  enabled: true
  font: "Arial"
  color: "#FFFF00"
  from_h: 2
  to_h: 13
  from_w: 80
  to_w: 98

burnin:
  mode: "blank"
  interval_sec: 300s
  duration_ms: 200